#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pika
Version  : 0.12.0
Release  : 24
URL      : http://pypi.debian.net/pika/pika-0.12.0.tar.gz
Source0  : http://pypi.debian.net/pika/pika-0.12.0.tar.gz
Summary  : Pika Python AMQP Client Library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pika-python3
Requires: pika-license
Requires: pika-python
Requires: tornado
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
====
        Pika is a RabbitMQ (AMQP-0-9-1) client library for Python.
        
        |Version| |Python versions| |Status| |Coverage| |License| |Docs|
        
        Introduction
        -------------
        Pika is a pure-Python implementation of the AMQP 0-9-1 protocol including RabbitMQ's
        extensions.
        
        - Python 2.7 and 3.4+ are supported.
        
        - Since threads aren't appropriate to every situation, it doesn't
          require threads. It takes care not to forbid them, either. The same
          goes for greenlets, callbacks, continuations and generators. It is
          not necessarily thread-safe however, and your mileage will vary.
        
        - People may be using direct sockets, plain old `select()`,
          or any of the wide variety of ways of getting network events to and from a
          python application. Pika tries to stay compatible with all of these, and to
          make adapting it to a new environment as simple as possible.
        
        Documentation
        -------------

%package license
Summary: license components for the pika package.
Group: Default

%description license
license components for the pika package.


%package python
Summary: python components for the pika package.
Group: Default
Requires: pika-python3

%description python
python components for the pika package.


%package python3
Summary: python3 components for the pika package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pika package.


%prep
%setup -q -n pika-0.12.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532270864
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/pika
cp LICENSE %{buildroot}/usr/share/doc/pika/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/pika/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
